[project]
name = "image-special-cource"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=9.2.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.2.3",
]
